name: Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Run Standard Ruby linter
        run: bin/standardrb

  test:
    name: Functional Testing
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Install libvips
        run: sudo apt install libvips libvips-dev libvips-tools

      - name: Run Tests with coverage
        run: bundle exec rake test
        env:
          COVERAGE: enabled

      - name: Upload Screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          path: test/fixtures/app/doc/screenshots/

      - name: Upload Coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage

  matrix:
    name: Test Integration
    needs: [ 'test', 'lint' ]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby-version: [ '2.7', '2.6', '2.5', 'jruby' ]
        gemfile: [ 'rails60_gems.rb', 'rails52.gemfile', 'rails51.gemfile', 'rails50.gemfile', 'rails42.gemfile' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Install libvips
        run: sudo apt install libvips libvips-dev libvips-tools

      - name: Run tests
        run: bundle exec rake test

  matrix_screenshot_driver:
    name: Test Integration
    needs: [ 'test', 'lint' ]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        screenshot-driver: [ 'vips', 'chunky_png' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Install libvips
        run: sudo apt install libvips libvips-dev libvips-tools

      - name: Run tests
        run: bundle exec rake test:integration
